### ISSUE TITLE
I can keep scrolling

### ISSUE THREAD

**Issue by Lars-Hoofs** [JulienMaille/spicetify-dynamic-theme#49] opened 2023-09-02 19:47 UTC
**Describe the bug**
On every page you can keep scrolling

**To Reproduce**
1. Play a song
2.  Scroll down

**Screenshots**
![image](https://github.com/JulienMaille/spicetify-dynamic-theme/assets/107960636/59c34c61-7fc4-44f9-9e94-b2ffa3cda9e5)

**Desktop Setup**
- Operating System: Windows 11
- Spotify: Spotify voor Windows (64-bits)
1.2.19.941.gbf202593
- Spicetify: Spicetify v2.23.0
- Theme:  Default Dynamic

** CSS Error **

This error can be disolved by just adding 'Body { Overflow : hidden;}'

**Comment by JulienMaille** [comment] 2023-09-02 21:04
Duplicate of #46

**Closed by JulienMaille** 2023-09-02 21:04 UTC
Labels: bug
